### ISSUE TITLE
Incompatible with `@ember/test-helpers` v4

### ISSUE THREAD

**Issue by boris-petrov** [elwayman02/ember-scroll-modifiers#1101] opened 2024-08-22 06:20 UTC
Congrats on the new release!

Updating `@ember/test-helpers` in my app to v4 lead to a build error:

`ember-scroll-modifiers tried to import "@ember/test-helpers" in "ember-scroll-modifiers/test-support/did-intersect-mock.js" from addon code, but "@ember/test-helpers" is a devDependency. You may need to move it into dependencies.`

Not sure what that means or why it happens but I guess you should try to do as it says. :smile: 

cc @elwayman02

**Comment by elwayman02** [comment] 2024-08-26 17:26
I need to add it as a peerDep, I believe. Will try to take a look at that this week.

**Comment by elwayman02** [comment] 2024-08-26 17:52
Issue reproduced here, so we should be able to test the fix locally by pushing commits to that branch: https://github.com/elwayman02/ember-scroll-modifiers/pull/1106

**Comment by elwayman02** [comment] 2024-08-26 18:41
It looks like there's an issue on the `@ember/test-helpers` side of things preventing us from adding it as a peerDep, I filed a ticket there: https://github.com/emberjs/ember-test-helpers/issues/1489

**Comment by elwayman02** [comment] 2024-08-26 18:56
nvm, I'm adding a fix now.

**Comment by elwayman02** [comment] 2024-08-26 19:24
Released in v7.2.1

**Closed by elwayman02** 2024-08-26 19:24 UTC
Labels: bug, help wanted, good first issue
